services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        working_dir: /var/www
        environment:
            - APP_ENV=${APP_ENV:-dev}
            - APP_DEBUG=${APP_DEBUG:-true}
            - LOG_PATH=${LOG_PATH:-/var/www/var/logs/app.log}
            - PROVIDER_CONFIG_PATH=${PROVIDER_CONFIG_PATH:-/var/www/config/providers.json}
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        ports:
            - "43434:80"
        volumes:
            - ./:/var/www
            - ./logs:/var/www/logs
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge