name: Quote Bundle Recommendation System API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8080:8080

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t app .

      - name: Run tests
        run: |
          docker run --rm app composer test

      - name: Run phpstan
        run: |
          docker run --rm app composer stan

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: php-test-results
          path: /var/www/html/tests/_output